export const genres = [
    'Fiction',
    'Non-fiction',
    'Mystery',
    'Thriller',
    'Romance',
    'Science Fiction',
    'Historical Fiction',
    'Fantasy',
    'Horror',
    'Adventure',
    'Biography',
    'Autobiography',
    'History',
    'Self-help',
    'Poetry',
    'Drama',
    'Comedy',
    'Suspense',
    'Crime',
    'Dystopian',
    'Young Adult',
    'Children',
    'Science',
    'Travel/Guidebooks',
    'Memoir',
    'Psychological',
    'Philosophical',
    'Religion/Spirituality',
    'Business',
    'Finance',
    'Politics',
    'Economics',
    'Art/Photography',
    'Music',
    'Sports',
    'Health/Fitness',
    'Parenting/Family',
    'Education',
    'Reference',
    'True Crime',
    'Paranormal',
    'Western',
    'Steampunk',
    'Time Travel',
    'Post-Apocalyptic',
    'Mythology/Folklore',
    'Classic Literature',
    'Modernist',
    'Coming-of-age',
    'Cooking',
    'Gothic',
    'Magical Realism',
    'Epic Poetry',
  ];

  const currentYear = new Date().getFullYear();
  export const years = Array.from(
    { length: currentYear - 1900 + 1 },
    (_, index) => 1900 + index
  );